name: Ruff
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: ruff
        run: |
          pip install ruff==0.11.10
          ruff check --verbose